example/WebAgent/Models/AcceptConnectionViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebAgent.Models
{
    public class AcceptConnectionViewModel
    {
        [Required]
        public string InvitationDetails { get; set; }
    }
}

example/WebAgent/Models/ConnectionsViewModel.cs
using System.Collections.Generic;
using Streetcred.Sdk.Model.Records;

namespace WebAgent.Models
{
    public class ConnectionsViewModel
    {
        public IEnumerable<ConnectionRecord> Connections { get; set; }

        public IEnumerable<ConnectionRecord> Invitations { get; set; }
    }
}

example/WebAgent/Models/ErrorViewModel.cs
namespace WebAgent.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

example/WebAgent/Controllers/ConnectionsController.cs
using System;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using Streetcred.Sdk.Contracts;
using Streetcred.Sdk.Extensions;
using Streetcred.Sdk.Extensions.Options;
using Streetcred.Sdk.Model.Connections;
using WebAgent.Models;

namespace WebAgent.Controllers
{
    public class ConnectionsController : Controller
    {
        private readonly IConnectionService _connectionService;
        private readonly IWalletService _walletService;
        private readonly IProvisioningService _provisioningService;
        private readonly WalletOptions _walletOptions;

        public ConnectionsController(
            IConnectionService connectionService, 
            IWalletService walletService, 
            IProvisioningService provisioningService, 
            IOptions<WalletOptions> walletOptions)
        {
            _connectionService = connectionService;
            _walletService = walletService;
            _provisioningService = provisioningService;
            _walletOptions = walletOptions.Value;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var wallet = await _walletService.GetWalletAsync(_walletOptions.WalletConfiguration, _walletOptions.WalletCredentials);
            return View(new ConnectionsViewModel
            {
                Connections = await _connectionService.ListAsync(wallet),
                Invitations = await _connectionService.ListNegotiatingConnectionsAsync(wallet)
            });
        }

        [HttpGet]
        public async Task<IActionResult> CreateInvitation()
        {
            var wallet = await _walletService.GetWalletAsync(_walletOptions.WalletConfiguration, _walletOptions.WalletCredentials);
            var provisioning = await _provisioningService.GetProvisioningAsync(wallet);

            var invitation = await _connectionService.CreateInvitationAsync(wallet,
                new DefaultCreateInviteConfiguration
                {
                    AutoAcceptConnection = true,
                    MyAlias = new ConnectionAlias {Name = provisioning.Owner.Name}
                });
            ViewData["Invitation"] = Convert.ToBase64String(Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(invitation)));
            return View();
        }

        [HttpGet]
        public IActionResult AcceptInvitation()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AcceptInvitation(AcceptConnectionViewModel model)
        {
            var invitationJson = Encoding.UTF8.GetString(Convert.FromBase64String(model.InvitationDetails));
            var invitation = JsonConvert.DeserializeObject<ConnectionInvitation>(invitationJson);

            var wallet = await _walletService.GetWalletAsync(_walletOptions.WalletConfiguration, _walletOptions.WalletCredentials);
            var _ = await _connectionService.AcceptInvitationAsync(wallet, invitation);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            var wallet = await _walletService.GetWalletAsync(_walletOptions.WalletConfiguration, _walletOptions.WalletCredentials);

            return View(await _connectionService.GetAsync(wallet, id));
        }
    }
}

example/WebAgent/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WebAgent.Models;

namespace WebAgent.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

example/WebAgent/Views/Connections/AcceptInvitation.cshtml
@model AcceptConnectionViewModel
@{
    ViewData["Title"] = "Create Invitation";
}
<h2>Accept Invitation</h2>
<p>
    Paste the connection invitation details
</p>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AcceptInvitation">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="InvitationDetails" class="control-label"></label>
                <input asp-for="InvitationDetails" class="form-control" />
                <span asp-validation-for="InvitationDetails" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Accept Invitation" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

example/WebAgent/Views/Connections/CreateInvitation.cshtml
<h1>
    Create Invitation
</h1>
<p>
    Copy the connection invitation details
</p>
<hr />
<div class="row">
    <div class="col-md-8">
        <form class="form-inline">
            <div class="form-group">
                <label class="sr-only" for="exampleInputAmount">Invitation Details</label>
                <div class="input-group">
                    <input type="text" class="form-control" readonly="readonly" id="exampleInputAmount" placeholder="Amount" value="@ViewData["Invitation"]" />
                </div>
            </div>
            <button class="btn btn-primary" onclick="copyToCliboard(document.getElementById('exampleInputAmount')); return false;">Copy to Clipboard</button>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

example/WebAgent/Views/Connections/Details.cshtml
@model Streetcred.Sdk.Model.Records.ConnectionRecord

<h4>Connection Details</h4>
<hr />
<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.ConnectionId)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.ConnectionId)
    </dd>
    
    <dt>
        @Html.DisplayNameFor(model => model.State)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.State)
    </dd>
    
    <dt>
        @Html.DisplayNameFor(model => model.MyDid)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.MyDid)
    </dd>
    
    <dt>
        @Html.DisplayNameFor(model => model.TheirDid)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.TheirDid)
    </dd>
</dl>

example/WebAgent/Views/Connections/Index.cshtml
@model ConnectionsViewModel

<hr />
<div class="btn-group pull-right">
    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="glyphicon glyphicon-send" aria-hidden="true"></span> Invitations <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
        <li><a asp-area="" asp-controller="Connections" asp-action="CreateInvitation">Create new invitation</a></li>
        <li role="separator" class="divider"></li>
        <li><a asp-area="" asp-controller="Connections" asp-action="AcceptInvitation">Accept invitation</a></li>
    </ul>
</div>
<div class="clearfix"></div>
@if (Model.Invitations.Any())
{
    <h2>Invitations</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Invitations)
            {
                <tr>
                    <td>
                        <a asp-area="" asp-controller="Connections" asp-action="Details" asp-route-id="@item.ConnectionId">@(item.Alias?.Name ?? item.ConnectionId)</a>
                    </td>
                    <td>
                        @item.State
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
@if (Model.Connections.Any())
{
    <h2>Connections</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Connections)
            {
                <tr>
                    <td>
                        <a asp-area="" asp-controller="Connections" asp-action="Details" asp-route-id="@item.ConnectionId">@(item.Alias?.Name ?? item.ConnectionId)</a>
                    </td>
                    <td>
                        @item.State
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

example/WebAgent/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}
<hr />
<div class="jumbotron">
    <h1>@Environment.GetEnvironmentVariable("STREETCRED_OWNER_NAME")'s Agent</h1>
    <p>
        Welcome! Feel free to look around, you can establish secure connections and exchange messages with other wizards and even muggles.
    </p>
    <p><a class="btn btn-primary btn-lg" asp-area="" asp-controller="Connections" asp-action="CreateInvitation" role="button">Go to Connections</a></p>
</div>

example/WebAgent/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
        @Environment.GetEnvironmentVariable("STREETCRED_OWNER_NAME")'s Agent
    </title>


        <environment include="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment exclude="Development">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">@Environment.GetEnvironmentVariable("STREETCRED_OWNER_NAME")'s Agent</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Connections" asp-action="Index">Connections</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr/>
        <footer>
            <p>&copy; 2018 - WebAgent</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>